
server:
  port: 8093
  servlet:
    context-path: /learning

spring:
  application:
    name:  test
  messages:
    basename: messages,messages_sys,messages_mst
    encoding: UTF-8
  datasource:
    druid:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        testOnReturn: false
        testWhileIdle: true
        maxActive: 30
        removeAbandoned: true
        name: datasource
        testOnBorrow: false
        minIdle: 10
        initialSize: 5
        poolPreparedStatements: true
        url: jdbc:mysql://58.87.106.44:3306/tms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: select 1
        maxOpenPreparedStatements: 300
        username: root
        password: 'Hsanwu123~'
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        testOnReturn: false
        testWhileIdle: true
        maxActive: 30
        removeAbandoned: true
        name: slaveDatasource    # DataSource命名要区分开，否则datasource 销毁时，会把同名的datasource一起销毁
        testOnBorrow: false
        minIdle: 10
        initialSize: 5
        poolPreparedStatements: true
        url: jdbc:mysql://58.87.106.44:3306/tms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: select 1
        maxOpenPreparedStatements: 300
        username: root
        password: 'Hsanwu123~'

  jackson:
    default-property-inclusion: non_null
#logging:
#  level:
#    root: trace

feign:
  hystrix:
    enabled: true
